[package]
name = "garntboy"
version = "0.1.0"
edition = "2021"

[lib]
name = "garntboy"
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
rust-libretro = "0.1.5"
rust-libretro-sys = "0.1.5"